version: "3"

services:

  postgres:
    image: "postgres:14"
    container_name: "english_school_db"
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "Dockerfile"
    command:
      - python srs/manage.py runserver 0.0.0.0:8000
    image: "support_app"
    container_name: "support_app"
    env_file: ".env"
    depends_on:
      postgres:
        condition: "service_healthy"
    volumes:
      - .:/microservice:rw
      - static_volume:/app/microservice/static
    expose:
      - "8000"

volumes:
  pg_data: {}
  static_volume: {}