# Generated by Django 4.1.8 on 2023-04-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="student",
            new_name="user",
        ),
    ]
