# Generated by Django 4.1.8 on 2023-05-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hometasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hometask",
            name="slug",
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
