# Generated by Django 4.1.8 on 2023-05-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hometasks", "0002_hometask_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hometask",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="createt_at"),
        ),
    ]
