# Generated by Django 4.1.8 on 2023-05-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hometasks", "0003_alter_hometask_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hometask",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="created_at"),
        ),
    ]
